# get all java class files under current directory NOT INCLUDING those with 'metadata' in the path or filename
# for each class file extract and report on the java minor and major versions
# this scheme might not work if we have too many files in the list generated by 'find'
for FILE in $(find . -name *.class | grep -v metadata)
do
  echo -n $FILE": "
  javap -verbose $FILE | grep -e 'major version' -e 'minor version' | awk '{print}' ORS=' '
  echo
done
